// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: seasons.sql

package sqlc

import (
	"context"
)

const getSeasonsForShow = `-- name: GetSeasonsForShow :many
SELECT id, legacy_id, tag_ids, number, age_rating, title, description, show_id, image FROM seasons WHERE show_id = ?
`

func (q *Queries) GetSeasonsForShow(ctx context.Context, showID int64) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonsForShow, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.LegacyID,
			&i.TagIds,
			&i.Number,
			&i.AgeRating,
			&i.Title,
			&i.Description,
			&i.ShowID,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
